FROM 133573815653.dkr.ecr.us-west-2.amazonaws.com/perceiver:1.13.1-neuronx-py310-sdk2.14.1-ubuntu20.04
FROM 133573815653.dkr.ecr.us-west-2.amazonaws.com/perceiver:2.0.1-cpu-py310-ubuntu20.04-ec2

RUN uname -a
RUN apt-get update --fix-missing
RUN apt-get install -y wget gnupg2 jq
ADD requirements.txt /requirements.txt

COPY * /
RUN pip install -r /requirements.txt
RUN mkdir /config
ADD config/main.yaml /config/main.yaml
RUN ls -l /
